/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_igeltech_nevercrypt_crypto_blockciphers_AES */

#ifndef _Included_com_igeltech_nevercrypt_crypto_blockciphers_AES
#define _Included_com_igeltech_nevercrypt_crypto_blockciphers_AES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_igeltech_nevercrypt_crypto_blockciphers_AES
 * Method:    initContext
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_igeltech_nevercrypt_crypto_blockciphers_AES_initContext
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_igeltech_nevercrypt_crypto_blockciphers_AES
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_igeltech_nevercrypt_crypto_blockciphers_AES_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_igeltech_nevercrypt_crypto_blockciphers_AES
 * Method:    encrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_igeltech_nevercrypt_crypto_blockciphers_AES_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_igeltech_nevercrypt_crypto_blockciphers_AES
 * Method:    decrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_igeltech_nevercrypt_crypto_blockciphers_AES_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
